### ISSUE TITLE
Test with clinical risk KP fails because data source changes

### ISSUE THREAD

**Issue by kevinxin90** [biothings/biothings_explorer#26]
> FAIL __test__/integration/TRAPIv1.test.js (97.982 s)
>   ● Testing endpoints › POST /v1/query with clinical risk kp query
> 
>     expect(received).toHaveProperty(path)
> 
>     Expected path: "MONDO:0005249"
>     Received path: []
> 
>     Received value: {}
> 
>       69 |                 expect(response.body.message.knowledge_graph).toHaveProperty("nodes");
>       70 |                 expect(response.body.message.knowledge_graph).toHaveProperty("edges");
>     > 71 |                 expect(response.body.message.knowledge_graph.nodes).toHaveProperty("MONDO:0005249")
>          |                                                                     ^
>       72 |             })
>       73 |     })
>       74 | 
> 
>       at __test__/integration/TRAPIv1.test.js:71:69
>       at Object.<anonymous> (__test__/integration/TRAPIv1.test.js:60:9)

**Comment by kevinxin90** [comment]
Fixed in: https://github.com/biothings/BioThings_Explorer_TRAPI/pull/28
