### ISSUE TITLE
automated tests failing due to async issue?

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#288]
This was something @marcodarko noticed. Leaving it to him to fill in this issue more, and decide who's being assigned, etc. 

Related to skipping tests in https://github.com/biothings/bte_trapi_query_graph_handler/commit/b2856d8ba4852009fd4f8188b73c3b81931a63c4 and https://github.com/biothings/smartapi-kg.js/commit/b85648bc0cd252758c98de8602931aa5b7d175cb

**Comment by colleenXu** [comment]
Note that I am also getting automated tests to fail that seem to be related to MyChem.info....even though the API is now up after being down sometime yesterday. Perhaps this test failure is related to async, maybe not...

**Comment by colleenXu** [comment]
A more recent example...

 PASS  __test__/utils.test.js
 PASS  __test__/ctd_transformer.test.js
 PASS  __test__/ebi_protein_transformer.test.js
 PASS  __test__/biolink_transformers.test.js
 PASS  __test__/base_transformer.test.js
 PASS  __test__/biothings_transformer.test.js
 FAIL  __test__/cord_transformer.test.js (6.203 s)
  ● test cord transformer › test cord pairInputWithAPIResponse

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test cord transformer › test cord pairInputWithAPIResponse

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new CordTransformer (built/transformers/cord_transformer.js:7:1)
      at Object.<anonymous> (__test__/cord_transformer.test.js:79:18)

  ● test cord transformer › test wrapper

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test cord transformer › test wrapper

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new CordTransformer (built/transformers/cord_transformer.js:7:1)
      at Object.<anonymous> (__test__/cord_transformer.test.js:86:18)

  ● test cord transformer › test json transform

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test cord transformer › test json transform

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new CordTransformer (built/transformers/cord_transformer.js:7:1)
      at Object.<anonymous> (__test__/cord_transformer.test.js:93:18)

  ● test cord transformer › add edge info

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test cord transformer › add edge info

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new CordTransformer (built/transformers/cord_transformer.js:7:1)
      at Object.<anonymous> (__test__/cord_transformer.test.js:99:18)

  ● test cord transformer › test main function transform

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test cord transformer › test main function transform

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new CordTransformer (built/transformers/cord_transformer.js:7:1)
      at Object.<anonymous> (__test__/cord_transformer.test.js:109:18)

 FAIL  __test__/transformers.test.js (7.027 s)
  ● test biothings transformer › test biothings pairInputWithAPIResponse

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test biothings transformer › test biothings pairInputWithAPIResponse

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at Object.<anonymous> (__test__/transformers.test.js:149:18)

  ● test biothings transformer › test wrapper

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test biothings transformer › test wrapper

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at Object.<anonymous> (__test__/transformers.test.js:157:18)

 FAIL  __test__/semmed_transformer.test.js (26.241 s)
  ● test semmed transformer › test semmed pairInputWithAPIResponse

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test semmed transformer › test semmed pairInputWithAPIResponse

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new SemmedTransformer (built/transformers/semmed_transformer.js:7:1)
      at Object.<anonymous> (__test__/semmed_transformer.test.js:80:18)

  ● test semmed transformer › test wrapper

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test semmed transformer › test wrapper

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new SemmedTransformer (built/transformers/semmed_transformer.js:7:1)
      at Object.<anonymous> (__test__/semmed_transformer.test.js:88:18)

  ● test semmed transformer › test json transform

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test semmed transformer › test json transform

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new SemmedTransformer (built/transformers/semmed_transformer.js:7:1)
      at Object.<anonymous> (__test__/semmed_transformer.test.js:94:18)

  ● test semmed transformer › add edge info

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test semmed transformer › add edge info

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new SemmedTransformer (built/transformers/semmed_transformer.js:7:1)
      at Object.<anonymous> (__test__/semmed_transformer.test.js:100:18)

  ● test semmed transformer › test main function transform

    Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.

      at mapper (../../../node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● test semmed transformer › test main function transform

    TypeError: Cannot read properties of undefined (reading 'edge')

      12 |     constructor(data) {
      13 |         this.data = data;
    > 14 |         this.edge = data.edge;
         |                          ^
      15 |     }
      16 |     /**
      17 |      * Create an object with key representing input, and value representing the output of API

      at new BaseTransformer (built/transformers/transformer.js:14:26)
      at new BioThingsTransformer (built/transformers/biothings_transformer.js:8:1)
      at new SemmedTransformer (built/transformers/semmed_transformer.js:7:1)
      at Object.<anonymous> (__test__/semmed_transformer.test.js:110:18)

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
Test Suites: 3 failed, 1 skipped, 6 passed, 9 of 10 total
Tests:       12 failed, 2 skipped, 31 passed, 45 total
Snapshots:   0 total
Time:        28.181 s

**Comment by colleenXu** [comment]
Unclear if this is still happening and it hasn't happened for a while. closing
