### ISSUE TITLE
updating BTE's docs/smartapi.yaml file to match registry

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#352]
Recently, I tried to update https://github.com/biothings/BioThings_Explorer_TRAPI/blob/main/docs/smartapi.yaml to match the [yaml we have registered in the smartapi registry](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/biothings_explorer/smartapi.yaml). The one in the smartapi registry is more recent, edited to match TRAPI 1.2 / current Translator standards. 

However, when I try replacing the docs/smartapi.yaml file and launching BTE, I encounter the error message below in Terminal. I think it has to do with stuff under paths and components/schemas....but I haven't figured out the exact problem or how to address it yet...

```
/Users/colleenxu/Desktop/bte-trapi-workspace/node_modules/api-schema-builder/src/index.js:43
    Object.keys(dereferenced.paths).forEach(currentPath => {
           ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at buildValidations (/Users/colleenxu/Desktop/bte-trapi-workspace/node_modules/api-schema-builder/src/index.js:43:12)
    at Object.buildSchemaSync (/Users/colleenxu/Desktop/bte-trapi-workspace/node_modules/api-schema-builder/src/index.js:31:12)
    at Middleware.init (/Users/colleenxu/Desktop/bte-trapi-workspace/node_modules/openapi-validator-middleware/src/middleware.js:33:41)
    at Object.<anonymous> (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/middlewares/validate.js:22:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by colleenXu** [comment]
should be resolved with https://github.com/biothings/BioThings_Explorer_TRAPI/commit/e0eafc51e387c0086094695b103cb501941c03de and https://github.com/NCATS-Tangerine/translator-api-registry/commit/7746b6ebd24b948281009ef16fc07f034d07938b

**Comment by colleenXu** [comment]
It's working fine now. Another commit has been made recently to fix a few things...https://github.com/biothings/BioThings_Explorer_TRAPI/commit/03486d8a7ab311233cc33d920285a20a899e39ca and https://github.com/NCATS-Tangerine/translator-api-registry/commit/0d32129658a196e352182369c9ccbd9ce5d5d13e
