### ISSUE TITLE
Node Normalizer errors show up as TRAPI validation errors

### ISSUE THREAD

**Issue by tokebe** [biothings/biothings_explorer#496]
Currently, when queries to the Node Normalizer fail, the error is logged as a TRAPI validation error, likely due to a specific catch statement in query handling. This makes error tracing take longer for devs.

See https://github.com/biothings/BioThings_Explorer_TRAPI/issues/492 as an example.

This should be fixed, either by changing whatever catch statement may be improperly catching these types of errors, or by some other means.

**Comment by rjawesome** [comment]
Two PRs made on both query_graph_handler and biomedical_id_resolver with fix_sri_error branch. Note that the query_graph_handler PR depends on the changes to biomedical_id_resolver.

**Comment by rjawesome** [comment]
Output from the example when SRI resolver is broken (I can also add special handling for SRIResolverFailiure similar to MetaKG and predicate loading errors if necessary in the bte main repo)
```
{
    "message": {
        "query_graph": {
            "edges": {
                "e0": {
                    "object": "n0",
                    "subject": "n1"
                },
                "e1": {
                    "object": "n2",
                    "subject": "n0"
                }
            },
            "nodes": {
                "n0": {
                    "categories": [
                        "biolink:DiseaseOrPhenotypicFeature"
                    ]
                },
                "n1": {
                    "ids": [
                        "NCBIGene:3605",
                        "NCBIGene:10758",
                        "NCBIGene:149233",
                        "NCBIGene:26191",
                        "NCBIGene:864",
                        "NCBIGene:51561"
                    ],
                    "is_set": true
                },
                "n2": {
                    "ids": [
                        "UBERON:0002384"
                    ]
                }
            }
        },
        "knowledge_graph": {
            "nodes": {},
            "edges": {}
        },
        "results": []
    },
    "status": 500,
    "description": "Error: SRI resolver failed: Request failed with status code 404",
    "trace": "SRIResolverFailiure: SRI resolver failed: Request failed with status code 404\n    at query (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/biomedical_id_resolver/built/sri.js:41:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object._resolveSRI (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/biomedical_id_resolver/built/sri.js:153:24)\n    at async Object.resolveSRI (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/biomedical_id_resolver/built/index.js:35:12)\n    at async QueryGraphHandler._findNodeCategories (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/query_graph.js:92:28)\n    at async QueryGraphHandler._storeNodes (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/query_graph.js:190:34)\n    at async QueryGraphHandler._storeEdges (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/query_graph.js:239:26)\n    at async QueryGraphHandler.calculateEdges (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/query_graph.js:266:26)\n    at async TRAPIQueryHandler._processQueryGraph (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/index.js:87:39)\n    at async TRAPIQueryHandler.query (/mnt/c/Users/User/Documents/Scripps/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/index.js:608:35)"
}
```
