### ISSUE TITLE
TRAPI implementation rules on QGraph "nulls"

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#498]
We'd like BTE to meet the requirements of the TRAPI [implementation rules](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationRules.md) when possible (and when they don't clash with other requirements/priorities we have for BTE). 

The implementation rules say that the following properties of a QGraph could have the value `null`. When the value is `null`, the property should be treated the same as if the property was missing / not there:
* [QNode.ids](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationRules.md#qnodeids)
* [QNode.categories](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationRules.md#qnodecategories)
* [QEdge.predicates](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/ImplementationRules.md#qedgepredicates)

---

Currently, this is what we do, with example queries (QGraphs) with `null`:

<details>
<summary>QNode.ids is `null`: we raise a ReferenceError</summary>

1-Hop Predict, so n1 doesn't need to have any values in the `ids` property. Desired behavior is to run this 1-hop without any errors/warnings in TRAPI logs or console logs.
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["NCBIGene:1742"],
                    "categories":["biolink:Gene"]
                },
                "n1": {
                    "ids": null,
                    "categories":["biolink:ChemicalEntity", "biolink:Procedure"]
               }
            },
            "edges": {
                "e1": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

Console logs. The request's response is TRAPI (empty KG and results sections), status 500, description `ReferenceError: id_resolver is not defined` and the trace gives all the info the error_handler put below. 

```
  bte:biothings-explorer-trapi:main MetaKG successfully loaded! +139ms
  bte:biothings-explorer-trapi:query_graph (1) Creating edges for manager... +2m
  bte:biothings-explorer-trapi:query_graph Query node missing categories...Looking for match... +342ms
  bte:biothings-explorer-trapi:NewQNode (1) Node "n0" has (1) entities at start. +2m
  bte:biothings-explorer-trapi:NewQNode (1) Node "n0" expanded initial curie. {"NCBIGene:1742":["NCBIGene:1742"]} +0ms
  bte:biothings-explorer-trapi:error_handler ReferenceError: id_resolver is not defined
  bte:biothings-explorer-trapi:error_handler     at TRAPIQueryHandler._processQueryGraph (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/index.js:111:73)
  bte:biothings-explorer-trapi:error_handler     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  bte:biothings-explorer-trapi:error_handler     at async TRAPIQueryHandler.query (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/index.js:627:35)
  bte:biothings-explorer-trapi:error_handler     at async task (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/routes/v1/query_v1.js:42:7)
  bte:biothings-explorer-trapi:error_handler     at async /Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/threading/threadHandler.js:93:38 +2m
```

</details>

<details>
<summary>QNode.categories is `null`: we raise a TypeError</summary>

1-Hop Predict. n0 doesn't need to have a `categories` value when an `ids` value is provided. Desired behavior is to run this 1-hop without any errors/warnings in TRAPI logs or console logs.

```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["NCBIGene:1742"],
                    "categories": null
                },
                "n1": {
                    "categories":["biolink:ChemicalEntity", "biolink:Procedure"]
               }
            },
            "edges": {
                "e1": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

Console logs. The request's response is TRAPI (empty KG and results sections), status 500, description `TypeError: Cannot read properties of null (reading 'includes')` and the trace gives all the info the error_handler put below. 

```
[nodemon] starting `node src/server.js`
  bte:biothings-explorer-trapi:EdgeReverse BioLink-model class is initiated. +0ms
  bte:biothings-explorer-trapi:cron SmartAPI sync disabled, server process 98316 disabling smartapi updates. +0ms
App listening at http://localhost:3000
  bte:biothings-explorer-trapi:error_handler TypeError: Cannot read properties of null (reading 'includes')
  bte:biothings-explorer-trapi:error_handler     at TRAPIQueryHandler.setQueryGraph (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/query_graph_handler/built/index.js:76:51)
  bte:biothings-explorer-trapi:error_handler     at task (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/routes/v1/query_v1.js:41:15)
  bte:biothings-explorer-trapi:error_handler     at /Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/threading/threadHandler.js:93:44
  bte:biothings-explorer-trapi:error_handler     at new Promise (<anonymous>)
  bte:biothings-explorer-trapi:error_handler     at runTask (/Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/controllers/threading/threadHandler.js:68:16)
  bte:biothings-explorer-trapi:error_handler     at /Users/colleenxu/Desktop/bte-trapi-workspace/packages/@biothings-explorer/bte-trapi/src/routes/v1/query_v1.js:22:34
  bte:biothings-explorer-trapi:error_handler     at Layer.handle [as handle_request] (/Users/colleenxu/Desktop/bte-trapi-workspace/node_modules/express/lib/router/layer.js:95:5)
  bte:biothings-explorer-trapi:error_handler     at next (/Users/colleenxu/Desktop/bte-trapi-workspace/node_modules/express/lib/router/route.js:144:13)
  bte:biothings-explorer-trapi:error_handler     at Middleware.validate [as validationMiddleware] (/Users/colleenxu/Desktop/bte-trapi-workspace/node_modules/openapi-validator-middleware/src/frameworks/express.js:7:9)
  bte:biothings-explorer-trapi:error_handler     at Middleware.validate (/Users/colleenxu/Desktop/bte-trapi-workspace/node_modules/openapi-validator-middleware/src/middleware.js:41:21) +0ms
```

</details>

<details>
<summary>QEdge.predicates is `null`: BTE looks for MetaEdges with predicate `null` and then exits execution</summary>

1-Hop Predict. We don't have to specify the predicates (then we allow any predicate for matching MetaEdges). Desired behavior is to run this 1-hop without any errors/warnings in TRAPI logs or console logs.
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids":["NCBIGene:1742"],
                    "categories":["biolink:Gene"]
                },
                "n1": {
                    "categories":["biolink:ChemicalEntity", "biolink:Procedure"]
               }
            },
            "edges": {
                "e1": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": null
                }
            }
        }
    }
}
```

Console logs, showing that BTE seems to think `null` is a predicate value to search MetaEdges for. The request's response is TRAPI (empty KG and results sections), logs say that no matching MetaEdges were found. 

```
  bte:biothings-explorer-trapi:edge-manager (3) Edge manager is managing 1 qEdges. +1m
  bte:biothings-explorer-trapi:edge-manager (4) Edges not yet executed = 1 +0ms
  bte:biothings-explorer-trapi:edge-manager (5) Sending next edge 'e1' WITH entity count...(1) +1ms
  bte:biothings-explorer-trapi:edge-manager Checking entity max : (0)--(1) +0ms
  bte:biothings-explorer-trapi:edge-manager 'e1' : (1) --> (0) +0ms
  bte:biothings-explorer-trapi:qedge2btedge Subject node is n0 +1m
  bte:biothings-explorer-trapi:qedge2btedge Object node is n1 +0ms
  bte:biothings-explorer-trapi:QueryExecutionEdge Expanded edges:  +2ms
  bte:biothings-explorer-trapi:QueryExecutionEdge Expanded edges:  +0ms
  bte:biothings-explorer-trapi:qedge2btedge KG Filters: {
  bte:biothings-explorer-trapi:qedge2btedge   "input_type": [
  bte:biothings-explorer-trapi:qedge2btedge     "Gene"
  bte:biothings-explorer-trapi:qedge2btedge   ],
  bte:biothings-explorer-trapi:qedge2btedge   "output_type": [
  bte:biothings-explorer-trapi:qedge2btedge     "MolecularEntity",
  bte:biothings-explorer-trapi:qedge2btedge     "SmallMolecule",
  bte:biothings-explorer-trapi:qedge2btedge     "NucleicAcidEntity",
  bte:biothings-explorer-trapi:qedge2btedge     "Exon",
  bte:biothings-explorer-trapi:qedge2btedge     "Transcript",
  bte:biothings-explorer-trapi:qedge2btedge     "RnaProduct",
  bte:biothings-explorer-trapi:qedge2btedge     "RnaProductIsoform",
  bte:biothings-explorer-trapi:qedge2btedge     "NoncodingRnaProduct",
  bte:biothings-explorer-trapi:qedge2btedge     "MicroRna",
  bte:biothings-explorer-trapi:qedge2btedge     "SiRna",
  bte:biothings-explorer-trapi:qedge2btedge     "CodingSequence",
  bte:biothings-explorer-trapi:qedge2btedge     "ChemicalMixture",
  bte:biothings-explorer-trapi:qedge2btedge     "MolecularMixture",
  bte:biothings-explorer-trapi:qedge2btedge     "Drug",
  bte:biothings-explorer-trapi:qedge2btedge     "ComplexMolecularMixture",
  bte:biothings-explorer-trapi:qedge2btedge     "ProcessedMaterial",
  bte:biothings-explorer-trapi:qedge2btedge     "Food",
  bte:biothings-explorer-trapi:qedge2btedge     "EnvironmentalFoodContaminant",
  bte:biothings-explorer-trapi:qedge2btedge     "FoodAdditive",
  bte:biothings-explorer-trapi:qedge2btedge     "Nutrient",
  bte:biothings-explorer-trapi:qedge2btedge     "Macronutrient",
  bte:biothings-explorer-trapi:qedge2btedge     "Micronutrient",
  bte:biothings-explorer-trapi:qedge2btedge     "Vitamin",
  bte:biothings-explorer-trapi:qedge2btedge     "ChemicalEntity",
  bte:biothings-explorer-trapi:qedge2btedge     "Procedure"
  bte:biothings-explorer-trapi:qedge2btedge   ],
  bte:biothings-explorer-trapi:qedge2btedge   "predicate": [
  bte:biothings-explorer-trapi:qedge2btedge     null
  bte:biothings-explorer-trapi:qedge2btedge   ]
  bte:biothings-explorer-trapi:qedge2btedge } +1ms
  bte:biothings-explorer-trapi:qedge2btedge No smartapi edge found for e1 +45ms
  bte:biothings-explorer-trapi:main Query Edge (e1) has no MetaKG edges. Your query terminates. +47ms
```

</details>

**Comment by colleenXu** [comment]
And a note, in case you're like me....`"null"` =/= `null`(I found this helpful https://stackoverflow.com/a/34360900)

EDIT: in the TRAPI spec, it uses `nullable: true` for [QNode.ids](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L601), [QNode.categories](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L607), and [QEdge.predicates](https://github.com/NCATSTranslator/ReasonerAPI/blob/master/TranslatorReasonerAPI.yaml#L662). This term is from [OpenAPI](https://swagger.io/docs/specification/data-models/data-types/)
