### ISSUE TITLE
RangeError: options.minThreads and options.maxThreads must not conflict

### ISSUE THREAD

**Issue by ngk5** [biothings/biothings_explorer#688]
Ran into the following error while starting BTE using Docker:

```
bte-trapi  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
bte-trapi  | RangeError: options.minThreads and options.maxThreads must not conflict
bte-trapi  |     at new Piscina (/home/node/app/node_modules/piscina/dist/src/index.js:684:19)
bte-trapi  |     at Object.<anonymous> (/home/node/app/src/controllers/threading/threadHandler.js:44:11)
bte-trapi  |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
bte-trapi  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
bte-trapi  |     at Module.load (node:internal/modules/cjs/loader:1076:32)
bte-trapi  |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
bte-trapi  |     at Module.require (node:internal/modules/cjs/loader:1100:19)
bte-trapi  |     at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
bte-trapi  |     at require (node:internal/modules/cjs/helpers:108:18)
bte-trapi  |     at Object.<anonymous> (/home/node/app/src/routes/v1/query_v1_by_api.js:13:46)
```

This error happened using the main branch version from 8/9/2023. 
Previous main branch version from 8/1/2023 did not have this error.

This [commit](https://github.com/biothings/biothings_explorer/commit/aefd7bfaffaf040d2e24caf59b163e786b10dd93) possibly caused this error. The change (eg. SYNC_CONCURRENCY_RATIO was reduced from 0.5 to 0.25) make it so that maxThreads could be less than or equal to minThreads if os.cpus().length <= 8.

Please fix!

**Comment by tokebe** [comment]
@ngk5 I've pushed a fix for this issue, please let us know if the problem persists or if any other issues come up!
