### ISSUE TITLE
Handling local instance "port in use" 

### ISSUE THREAD

**Issue by colleenXu** [biothings/biothings_explorer#805]
Jackson and I consider this low-priority. But fairly easy to write some improvements (to pnpm stop?) to help with this. 

---

This is a situation I've encountered locally several times. I only captured the workflow to recreate the error recently:

* have an active local BTE instance open (using port 3000)
* update one of BTE's files (in the src folder of a module) - these are being monitored for changes
* as soon as you save that update, the active BTE instance will start rebuilding. **During this process, ctrl-C several times.** Based on the console logs, BTE won't actually quit until the rebuilding process is done. 
* Then try to start up BTE again. BTE will throw the error saying this port is in use. 
* Trying to run `pnpm stop` won't help. 
* The current methods to address this are:
    * kill the process using port 3000 with `lsof -ti:3000 | xargs kill -9`
    * try to avoid this situation: if I accidentally trigger a rebuild, let it finish before stopping BTE with ctrl-C. 

<details><summary>Console logs during rebuild + ctrl-c input</summary>
<p>

```
[nodemon] restarting due to changes...
[nodemon] starting `pnpm run build && node . ./packages/**/data/*`

> @biothings-explorer/bte-trapi@3.0.0 build /Users/colleenxu/Desktop/biothings_explorer
> turbo run build

╭───────────────────────────────────────────────────────────────────────╮
│                                                                       │
│                  Update available v1.13.0 ≫ v1.13.2                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.13.2    │
│           Run "npx @turbo/codemod@latest update" to update            │
│                                                                       │
│        Follow @turborepo for updates: https://x.com/turborepo         │
╰───────────────────────────────────────────────────────────────────────╯
• Packages in scope: @biothings-explorer/api-response-transform, @biothings-explorer/bte-server, @biothings-explorer/call-apis, @biothings-explorer/node-expansion, @biothings-explorer/query_graph_handler, @biothings-explorer/smartapi-kg, @biothings-explorer/types, @biothings-explorer/utils, @marcodarko/btewebapp, biolink-model, biomedical_id_resolver
• Running build in 11 packages
• Remote caching disabled
@biothings-explorer/node-expansion:build: cache hit (outputs already on disk), replaying logs 4fbf620e98c022d8
@marcodarko/btewebapp:build: cache hit (outputs already on disk), replaying logs d9166b849b202476
@biothings-explorer/node-expansion:build: 
@biothings-explorer/node-expansion:build: > @biothings-explorer/node-expansion@1.0.1 build /Users/colleenxu/Desktop/biothings_explorer/packages/node-expansion
@biothings-explorer/node-expansion:build: > tsc -b
@biothings-explorer/node-expansion:build: 
@marcodarko/btewebapp:build: 
@marcodarko/btewebapp:build: > @marcodarko/btewebapp@1.0.8 build /Users/colleenxu/Desktop/biothings_explorer/packages/web-app
@marcodarko/btewebapp:build: > vite build
@marcodarko/btewebapp:build: 
@marcodarko/btewebapp:build: vite v3.2.7 building for production...
✓ 344 modules transformed.
dist/assets/ncats-logo.f82e9583.png     15.78 KiB
@marcodarko/btewebapp:build: dist/assets/nih-logo.0ec775d8.png       59.07 KiB
@marcodarko/btewebapp:build: dist/assets/scripps-logo.d1e0e4e4.png   81.09 KiB
@marcodarko/btewebapp:build: dist/assets/network-01.53f6646d.svg     10.59 KiB
@marcodarko/btewebapp:build: dist/assets/network-2-01.6f8a0493.svg   2.54 KiB
@marcodarko/btewebapp:build: dist/index.html                         0.47 KiB
@marcodarko/btewebapp:build: dist/assets/AboutView.81de67cf.js       5.59 KiB / gzip: 2.06 KiB
@marcodarko/btewebapp:build: dist/assets/Try.2ffac24d.css            0.55 KiB / gzip: 0.18 KiB
@marcodarko/btewebapp:build: dist/assets/index.0ade1f1b.css          20.10 KiB / gzip: 4.89 KiB
@marcodarko/btewebapp:build: dist/assets/index.ca2a4357.js           181.54 KiB / gzip: 63.88 KiB
@marcodarko/btewebapp:build: dist/assets/cytoscape.cjs.75aa3387.js   358.97 KiB / gzip: 115.72 KiB
@marcodarko/btewebapp:build: dist/assets/Try.7075c0ec.js             472.38 KiB / gzip: 156.01 KiB
@biothings-explorer/smartapi-kg:build: cache hit (outputs already on disk), replaying logs 3f1e606ccc721c26
biolink-model:build: cache hit (outputs already on disk), replaying logs c8b8baef189032ef
@biothings-explorer/utils:build: cache hit (outputs already on disk), replaying logs 318c4e69a83f2306
@biothings-explorer/utils:build: 
@biothings-explorer/smartapi-kg:build: 
@biothings-explorer/smartapi-kg:build: > @biothings-explorer/smartapi-kg@4.0.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/smartapi-kg
@biothings-explorer/smartapi-kg:build: > tsc --project ./
@biothings-explorer/smartapi-kg:build: 
biolink-model:build: 
biolink-model:build: > biolink-model@0.4.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/biolink-model
biolink-model:build: > tsc -b
biolink-model:build: 
@biothings-explorer/utils:build: > @biothings-explorer/utils@1.0.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/utils
@biothings-explorer/utils:build: > tsc -b
@biothings-explorer/utils:build: 
@biothings-explorer/api-response-transform:build: cache hit (outputs already on disk), replaying logs e4752862ac266c8e
biomedical_id_resolver:build: cache hit (outputs already on disk), replaying logs f1ddc8b7854e0110
@biothings-explorer/types:build: cache hit (outputs already on disk), replaying logs e4c5a271533d0db4
@biothings-explorer/api-response-transform:build: 
biomedical_id_resolver:build: 
biomedical_id_resolver:build: > biomedical_id_resolver@3.11.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/biomedical_id_resolver
biomedical_id_resolver:build: > tsc -b
@biothings-explorer/types:build: 
@biothings-explorer/types:build: > @biothings-explorer/types@1.0.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/types
biomedical_id_resolver:build: 
@biothings-explorer/types:build: > tsc -b
@biothings-explorer/types:build: 
@biothings-explorer/api-response-transform:build: > @biothings-explorer/api-response-transform@1.12.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/api-response-transform
@biothings-explorer/api-response-transform:build: > tsc -b
@biothings-explorer/api-response-transform:build: 
@biothings-explorer/call-apis:build: cache hit (outputs already on disk), replaying logs 758e09f474223320
@biothings-explorer/call-apis:build: 
@biothings-explorer/call-apis:build: > @biothings-explorer/call-apis@1.24.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/call-apis
@biothings-explorer/call-apis:build: > tsc -b
@biothings-explorer/call-apis:build: 
@biothings-explorer/query_graph_handler:build: cache hit (outputs already on disk), replaying logs cc47044e450ef989
@biothings-explorer/query_graph_handler:build: 
@biothings-explorer/query_graph_handler:build: > @biothings-explorer/query_graph_handler@1.18.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/query_graph_handler
@biothings-explorer/query_graph_handler:build: > tsc -b
@biothings-explorer/query_graph_handler:build: 
@biothings-explorer/bte-server:build: cache miss, executing 35aa4ef6943b3d5c
^C    ...Finishing writing to cache...                                                                                              @biothings-explorer/bte-server:build: 
 ERROR  run failed: command  exited (1)
➜  biothings_explorer git:(main) ✗                                                                               [2/04/24| 7:46PM] 
➜  biothings_explorer git:(main) ✗   bte:biothings-explorer-trapi:bullboard Initializing Bull Dashboard +0ms     [2/04/24| 7:46PM] 
  bte:biothings-explorer-trapi:bullboard Redis is not enabled, disabling Bull Dashboard +2ms
  bte:biothings-explorer-trapi:cron SmartAPI sync disabled, server process 20477 disabling smartapi updates. +0ms
  bte:biothings-explorer-trapi:server-start Instance Env: ci +0ms
⭐⭐⭐ BioThings Explorer is ready! ⭐ Try it now @ http://localhost:3000 ✨

➜  biothings_explorer git:(main) ✗
```

</p>
</details> 

<details><summary>Console logs showing "port in use" error when trying to restart BTE after ctrl-C</summary>
<p>

```
➜  biothings_explorer git:(main) ✗ INSTANCE_ENV=ci USE_THREADING=false pnpm start                                [2/04/24| 7:47PM] 

> @biothings-explorer/bte-trapi@3.0.0 start /Users/colleenxu/Desktop/biothings_explorer
> ./scripts/start_server.sh


> @biothings-explorer/bte-trapi@3.0.0 debug /Users/colleenxu/Desktop/biothings_explorer
> DEBUG=biomedical-id-resolver,bte* pnpm run watch


> @biothings-explorer/bte-trapi@3.0.0 watch /Users/colleenxu/Desktop/biothings_explorer
> nodemon -e js,mjs,json,ts --watch './packages/**/src/*' './packages/**/data/*' --exec 'pnpm run build && node .'

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): packages/**/src/**/*
[nodemon] watching extensions: js,mjs,json,ts
[nodemon] starting `pnpm run build && node . ./packages/**/data/*`

> @biothings-explorer/bte-trapi@3.0.0 build /Users/colleenxu/Desktop/biothings_explorer
> turbo run build

╭───────────────────────────────────────────────────────────────────────╮
│                                                                       │
│                  Update available v1.13.0 ≫ v1.13.2                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.13.2    │
│           Run "npx @turbo/codemod@latest update" to update            │
│                                                                       │
│        Follow @turborepo for updates: https://x.com/turborepo         │
╰───────────────────────────────────────────────────────────────────────╯
• Packages in scope: @biothings-explorer/api-response-transform, @biothings-explorer/bte-server, @biothings-explorer/call-apis, @biothings-explorer/node-expansion, @biothings-explorer/query_graph_handler, @biothings-explorer/smartapi-kg, @biothings-explorer/types, @biothings-explorer/utils, @marcodarko/btewebapp, biolink-model, biomedical_id_resolver
• Running build in 11 packages
• Remote caching disabled
biolink-model:build: cache hit (outputs already on disk), replaying logs c8b8baef189032ef
@biothings-explorer/node-expansion:build: cache hit (outputs already on disk), replaying logs 4fbf620e98c022d8
@biothings-explorer/smartapi-kg:build: cache hit (outputs already on disk), replaying logs 3f1e606ccc721c26
@marcodarko/btewebapp:build: cache hit (outputs already on disk), replaying logs d9166b849b202476
@biothings-explorer/utils:build: cache hit (outputs already on disk), replaying logs 318c4e69a83f2306
biolink-model:build: 
@biothings-explorer/utils:build: 
biolink-model:build: > biolink-model@0.4.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/biolink-model
biolink-model:build: > tsc -b
biolink-model:build: 
@biothings-explorer/utils:build: > @biothings-explorer/utils@1.0.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/utils
@biothings-explorer/utils:build: > tsc -b
@biothings-explorer/utils:build: 
@biothings-explorer/node-expansion:build: 
@biothings-explorer/smartapi-kg:build: 
@biothings-explorer/smartapi-kg:build: > @biothings-explorer/smartapi-kg@4.0.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/smartapi-kg
@biothings-explorer/smartapi-kg:build: > tsc --project ./
@biothings-explorer/node-expansion:build: > @biothings-explorer/node-expansion@1.0.1 build /Users/colleenxu/Desktop/biothings_explorer/packages/node-expansion
@marcodarko/btewebapp:build: 
@marcodarko/btewebapp:build: > @marcodarko/btewebapp@1.0.8 build /Users/colleenxu/Desktop/biothings_explorer/packages/web-app
@biothings-explorer/node-expansion:build: > tsc -b
@biothings-explorer/node-expansion:build: 
@biothings-explorer/smartapi-kg:build: 
@marcodarko/btewebapp:build: > vite build
@marcodarko/btewebapp:build: 
@marcodarko/btewebapp:build: vite v3.2.7 building for production...
✓ 344 modules transformed.
dist/assets/ncats-logo.f82e9583.png     15.78 KiB
@marcodarko/btewebapp:build: dist/assets/nih-logo.0ec775d8.png       59.07 KiB
@marcodarko/btewebapp:build: dist/assets/scripps-logo.d1e0e4e4.png   81.09 KiB
@marcodarko/btewebapp:build: dist/assets/network-01.53f6646d.svg     10.59 KiB
@marcodarko/btewebapp:build: dist/assets/network-2-01.6f8a0493.svg   2.54 KiB
@marcodarko/btewebapp:build: dist/index.html                         0.47 KiB
@marcodarko/btewebapp:build: dist/assets/AboutView.81de67cf.js       5.59 KiB / gzip: 2.06 KiB
@marcodarko/btewebapp:build: dist/assets/Try.2ffac24d.css            0.55 KiB / gzip: 0.18 KiB
@marcodarko/btewebapp:build: dist/assets/index.0ade1f1b.css          20.10 KiB / gzip: 4.89 KiB
@marcodarko/btewebapp:build: dist/assets/index.ca2a4357.js           181.54 KiB / gzip: 63.88 KiB
@marcodarko/btewebapp:build: dist/assets/cytoscape.cjs.75aa3387.js   358.97 KiB / gzip: 115.72 KiB
@marcodarko/btewebapp:build: dist/assets/Try.7075c0ec.js             472.38 KiB / gzip: 156.01 KiB
@biothings-explorer/types:build: cache hit (outputs already on disk), replaying logs e4c5a271533d0db4
@biothings-explorer/types:build: 
@biothings-explorer/types:build: > @biothings-explorer/types@1.0.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/types
@biothings-explorer/types:build: > tsc -b
@biothings-explorer/types:build: 
@biothings-explorer/api-response-transform:build: cache hit (outputs already on disk), replaying logs e4752862ac266c8e
biomedical_id_resolver:build: cache hit (outputs already on disk), replaying logs f1ddc8b7854e0110
@biothings-explorer/api-response-transform:build: 
@biothings-explorer/api-response-transform:build: > @biothings-explorer/api-response-transform@1.12.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/api-response-transform
@biothings-explorer/api-response-transform:build: > tsc -b
@biothings-explorer/api-response-transform:build: 
biomedical_id_resolver:build: 
biomedical_id_resolver:build: > biomedical_id_resolver@3.11.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/biomedical_id_resolver
biomedical_id_resolver:build: > tsc -b
biomedical_id_resolver:build: 
@biothings-explorer/call-apis:build: cache hit (outputs already on disk), replaying logs 758e09f474223320
@biothings-explorer/call-apis:build: 
@biothings-explorer/call-apis:build: > @biothings-explorer/call-apis@1.24.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/call-apis
@biothings-explorer/call-apis:build: > tsc -b
@biothings-explorer/call-apis:build: 
@biothings-explorer/query_graph_handler:build: cache hit (outputs already on disk), replaying logs cc47044e450ef989
@biothings-explorer/query_graph_handler:build: 
@biothings-explorer/query_graph_handler:build: > @biothings-explorer/query_graph_handler@1.18.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/query_graph_handler
@biothings-explorer/query_graph_handler:build: > tsc -b
@biothings-explorer/query_graph_handler:build: 
@biothings-explorer/bte-server:build: cache miss, executing 35aa4ef6943b3d5c
@biothings-explorer/bte-server:build: 
@biothings-explorer/bte-server:build: > @biothings-explorer/bte-server@3.0.0 build /Users/colleenxu/Desktop/biothings_explorer/packages/bte-server
@biothings-explorer/bte-server:build: > tsc -b
@biothings-explorer/bte-server:build: 

 Tasks:    11 successful, 11 total
Cached:    10 cached, 11 total
  Time:    4.137s 

  bte:biothings-explorer-trapi:bullboard Initializing Bull Dashboard +0ms
  bte:biothings-explorer-trapi:bullboard Redis is not enabled, disabling Bull Dashboard +1ms
  bte:biothings-explorer-trapi:cron SmartAPI sync disabled, server process 20723 disabling smartapi updates. +0ms
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at Function.listen (/Users/colleenxu/Desktop/biothings_explorer/node_modules/.pnpm/express@4.18.3_supports-color@7.2.0/node_modules/express/lib/application.js:635:24)
    at main (/Users/colleenxu/Desktop/biothings_explorer/packages/bte-server/built/server.js:37:9)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v18.19.0
[nodemon] app crashed - waiting for file changes before starting...
^C%                                                                       
```

</p>
</details> 

<details><summary>Console logs when trying to use pnpm stop</summary>
<p>

```
➜  biothings_explorer git:(main) ✗ pnpm stop                                                                     [2/04/24| 7:47PM] 

> @biothings-explorer/bte-trapi@3.0.0 stop /Users/colleenxu/Desktop/biothings_explorer
> ./scripts/stop_server.sh

BTE subprocesses stopped.
BTE Stopped.
./scripts/stop_server.sh: line 6: docker: command not found
 ELIFECYCLE  Command failed with exit code 1.
```

</p>
</details> 

<details><summary>Console logs when killing process using port 3000</summary>
<p>

```
➜  biothings_explorer git:(main) ✗ lsof -ti:3000 | xargs kill -9                                                 [2/04/24| 7:47PM] 
sh: line 1: 20477 Killed: 9               node . ./packages/**/data/*    
```

</p>
</details>

**Comment by tokebe** [comment]
This could be addressed either with improvements to the `pnpm stop` script or `pnpm start`, with some detection of the error and prompting the user if they wish to kill the previous instance.
